import { and, desc, eq, gte } from "drizzle-orm";
import { db } from "@/db";
import { cdfEvents, cdfScores, cdfSettings } from "@/db/schema";
import { getGrade, type CdfEventDTO, type CdfEventGroup, type CdfScoreDTO, type CdfSettingsDTO, type CreateCdfEventInput, type SubmitFocusInput } from "@/types/cdf";

type Event = typeof cdfEvents.$inferSelect;
type Score = typeof cdfScores.$inferSelect;
const windowStart = () => new Date(Date.now() - 30 * 86_400_000);
const eventDto = (e: Event): CdfEventDTO => ({ id: e.id, taskId: e.taskId, taskTitle: e.taskTitle, listId: e.listId, repeat: e.repeat, dueDate: e.dueDate?.toISOString().split("T")[0] ?? null, dueTime: e.dueTime, completedAt: e.completedAt.toISOString(), onTime: e.onTime, lateByMs: e.lateByMs, focusScore: e.focusScore, focusEnteredAt: e.focusEnteredAt?.toISOString() ?? null, createdAt: e.createdAt.toISOString() });
const scoreDto = (s: Score): CdfScoreDTO => { const overallScore = Math.round(s.consistencyScore * .4 + s.disciplineScore * .35 + s.focusScore * .25); return { consistencyScore: s.consistencyScore, consistencyStreak: s.consistencyStreak, longestStreak: s.longestStreak, totalExpected: s.totalExpected, totalCompleted: s.totalCompleted, disciplineScore: s.disciplineScore, onTimeCount: s.onTimeCount, totalTimedTasks: s.totalTimedTasks, focusScore: s.focusScore, focusEntries: s.focusEntries, windowStart: s.windowStart.toISOString(), windowEnd: s.windowEnd.toISOString(), lastCalculatedAt: s.lastCalculatedAt.toISOString(), consistencyGrade: getGrade(s.consistencyScore), disciplineGrade: getGrade(s.disciplineScore), focusGrade: getGrade(s.focusScore), overallScore }; };
function timing(date: string | null, time: string | null, completed: Date) { if (!date || !time) return { onTime: true, lateByMs: 0 }; const deadline = new Date(date); const [h, m] = time.split(":").map(Number); deadline.setHours(h, m, 0, 0); const limit = deadline.getTime() + 60_000; return { onTime: completed.getTime() <= limit, lateByMs: Math.max(0, completed.getTime() - limit) }; }
async function recalculate(userId: string) {
  const start = windowStart(), end = new Date();
  const events = await db.select().from(cdfEvents).where(and(eq(cdfEvents.userId, userId), gte(cdfEvents.completedAt, start)));
  const repeat = events.filter((e) => e.repeat !== "none"), timed = events.filter((e) => e.dueTime), focused = events.filter((e) => e.focusScore !== null);
  const expected: Record<string, number> = { daily: 30, weekdays: 22, weekly: 4, monthly: 1, yearly: 0 };
  const unique = new Map(repeat.map((e) => [e.taskId, e.repeat])); const totalExpected = [...unique.values()].reduce((n, r) => n + (expected[r] ?? 0), 0);
  const dates = new Set(repeat.map((e) => e.completedAt.toISOString().slice(0, 10))); let streak = 0; for (let i = 0; i < 30; i++) { const d = new Date(); d.setDate(d.getDate() - i); if (!dates.has(d.toISOString().slice(0, 10))) break; streak++; }
  const values = { consistencyScore: totalExpected ? Math.round(repeat.length / totalExpected * 100) : 0, consistencyStreak: streak, longestStreak: streak, totalExpected, totalCompleted: repeat.length, disciplineScore: timed.length ? Math.round(timed.filter((e) => e.onTime).length / timed.length * 100) : 0, onTimeCount: timed.filter((e) => e.onTime).length, totalTimedTasks: timed.length, focusScore: focused.length ? Math.round(focused.reduce((n, e) => n + (e.focusScore ?? 0), 0) / focused.length) : 0, focusEntries: focused.length, focusTotal: focused.reduce((n, e) => n + (e.focusScore ?? 0), 0), windowStart: start, windowEnd: end, lastCalculatedAt: end, updatedAt: end };
  await db.insert(cdfScores).values({ userId, ...values }).onConflictDoUpdate({ target: cdfScores.userId, set: values });
}
export async function getCdfSettings(userId: string): Promise<CdfSettingsDTO> { const s = (await db.select().from(cdfSettings).where(eq(cdfSettings.userId, userId)).limit(1))[0]; return { enabled: s?.enabled ?? false, updatedAt: (s?.updatedAt ?? new Date()).toISOString() }; }
export async function updateCdfSettings(userId: string, enabled: boolean): Promise<CdfSettingsDTO> { const [s] = await db.insert(cdfSettings).values({ userId, enabled }).onConflictDoUpdate({ target: cdfSettings.userId, set: { enabled, updatedAt: new Date() } }).returning(); return { enabled: s.enabled, updatedAt: s.updatedAt.toISOString() }; }
export async function isCdfEnabled(userId: string) { return (await getCdfSettings(userId)).enabled; }
export async function createCdfEvent(userId: string, input: CreateCdfEventInput) { const completedAt = new Date(); const [event] = await db.insert(cdfEvents).values({ userId, taskId: input.taskId, taskTitle: input.taskTitle, listId: input.listId, repeat: input.repeat, dueDate: input.dueDate ? new Date(input.dueDate) : null, dueTime: input.dueTime, completedAt, ...timing(input.dueDate, input.dueTime, completedAt) }).returning(); void recalculate(userId); return eventDto(event); }
export async function submitFocusScore(userId: string, id: string, input: SubmitFocusInput) { if (input.focusScore < 0 || input.focusScore > 100) throw new Error("INVALID_FOCUS_SCORE"); const [event] = await db.update(cdfEvents).set({ focusScore: Math.round(input.focusScore), focusEnteredAt: new Date(), updatedAt: new Date() }).where(and(eq(cdfEvents.id, id), eq(cdfEvents.userId, userId))).returning(); if (!event) throw new Error("EVENT_NOT_FOUND"); void recalculate(userId); return eventDto(event); }
export async function getCdfScores(userId: string) { const score = (await db.select().from(cdfScores).where(eq(cdfScores.userId, userId)).limit(1))[0]; return score ? scoreDto(score) : null; }
export async function getCdfEvents(userId: string, limit = 50): Promise<CdfEventGroup[]> { const events = (await db.select().from(cdfEvents).where(and(eq(cdfEvents.userId, userId), gte(cdfEvents.completedAt, windowStart()))).orderBy(desc(cdfEvents.completedAt)).limit(limit)).map(eventDto); const groups: CdfEventGroup[] = [{ label: "Today", events: [] }, { label: "Yesterday", events: [] }, { label: "Last 7 Days", events: [] }, { label: "Older", events: [] }]; const today = new Date(); today.setHours(0, 0, 0, 0); for (const e of events) { const days = Math.floor((today.getTime() - new Date(e.completedAt).setHours(0, 0, 0, 0)) / 86_400_000); groups[days <= 0 ? 0 : days === 1 ? 1 : days <= 7 ? 2 : 3].events.push(e); } return groups.filter((g) => g.events.length); }
export const CDF_ERRORS = { INVALID_ID: { status: 400, message: "Invalid ID format." }, EVENT_NOT_FOUND: { status: 404, message: "CDF event not found." }, INVALID_FOCUS_SCORE: { status: 400, message: "Focus score must be between 0-100." } };
export function resolveCdfError(error: unknown) { return CDF_ERRORS[error instanceof Error ? error.message as keyof typeof CDF_ERRORS : "INVALID_ID"] ?? { status: 500, message: "Something went wrong." }; }
